#  DataFrame

# 创建方式

In [1]:
from operator import index

import pandas as pd
import numpy as np

In [2]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
df = pd.DataFrame({
    "第一列":s1,
    "第二列":s2
})
df.dtypes
type(df)
type(s1)
type(s2)
# 通过字典来创建
df = pd.DataFrame(
    {

        "name":['tom', 'tom',"jack", "alice", "bob", "allen"],
        "age":[15, 15,15, 20, 26, 30],
        "score":[60.5, 60.5,80 ,30.6, 70, 83.5 ]
    }, index=[1,2,3,4,5, 6], columns=["name","score","age"]
)
df

    name  score  age
1    tom   60.5   15
2    tom   60.5   15
3   jack   80.0   15
4  alice   30.6   20
5    bob   70.0   26
6  allen   83.5   30

# 属性

In [3]:
print(df.index)      # 行索引
print(df.columns)    # 列标签
print(df.values)     #值

Index([1, 2, 3, 4, 5, 6], dtype='int64')
Index(['name', 'score', 'age'], dtype='object')
[['tom' 60.5 15]
 ['tom' 60.5 15]
 ['jack' 80.0 15]
 ['alice' 30.6 20]
 ['bob' 70.0 26]
 ['allen' 83.5 30]]

In [4]:
print(df.ndim)   # 维度
print(df.dtypes)  #数据类型
print(df.shape)  #形状
print(df.size)   # 元素个数

2
name      object
score    float64
age        int64
dtype: object
(6, 3)
18

In [5]:
print(df.T)

          1     2     3      4     5      6
name    tom   tom  jack  alice   bob  allen
score  60.5  60.5  80.0   30.6  70.0   83.5
age      15    15    15     20    26     30

# 获取元素  loc iloc at iat

In [6]:
df
print(df.loc[4])

name     alice
score     30.6
age         20
Name: 4, dtype: object

In [7]:
print(df.iloc[3])         # 隐式索引  从 0 开始

name     alice
score     30.6
age         20
Name: 4, dtype: object

In [8]:
print(df.loc[:,'name'])
print(df.iloc[:, 0])

1      tom
2      tom
3     jack
4    alice
5      bob
6    allen
Name: name, dtype: object
1      tom
2      tom
3     jack
4    alice
5      bob
6    allen
Name: name, dtype: object

In [9]:
# 单个数据

print(df.at[3, 'score'])
print(df.iat[2, 1])        # loc 一样

80.0
80.0

In [10]:
#单列数据
print(df["name"])
print(type(df["name"]))
print(df.name)
print(type(df.name))
print(df[["name"]])
print(type(df[["name"]]))
df[["name"]]

1      tom
2      tom
3     jack
4    alice
5      bob
6    allen
Name: name, dtype: object
<class 'pandas.core.series.Series'>
1      tom
2      tom
3     jack
4    alice
5      bob
6    allen
Name: name, dtype: object
<class 'pandas.core.series.Series'>
    name
1    tom
2    tom
3   jack
4  alice
5    bob
6  allen
<class 'pandas.core.frame.DataFrame'>

    name
1    tom
2    tom
3   jack
4  alice
5    bob
6  allen

In [11]:
# 多列数据
print(df[["name", "score"]])

    name  score
1    tom   60.5
2    tom   60.5
3   jack   80.0
4  alice   30.6
5    bob   70.0
6  allen   83.5

In [12]:
#查看部分数据
print(df.tail(3))
print(df.head(3))

    name  score  age
4  alice   30.6   20
5    bob   70.0   26
6  allen   83.5   30
   name  score  age
1   tom   60.5   15
2   tom   60.5   15
3  jack   80.0   15

In [13]:
# 布尔索引

df[df.score>70]
df[(df.score>70) & (df.age<20)]

   name  score  age
3  jack   80.0   15

In [14]:
# 随机抽样
df.sample(3)

    name  score  age
3   jack   80.0   15
4  alice   30.6   20
1    tom   60.5   15

# 常用方法

In [15]:
print(df.isin(["jack", 20]))        # 查看元素是否出现在集合中

    name  score    age
1  False  False  False
2  False  False  False
3   True  False  False
4  False  False   True
5  False  False  False
6  False  False  False

In [16]:
print(df.isna())         # 查看是否是缺失值

    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False

In [17]:
print(df['score'].sum())       # 某一列 的 和
print(df['age'].min())
print(df.score.mean())
print(df.score.std())
print(df.score.median())
print(df.score.mode())

385.1
15
64.18333333333334
19.037375519400424
65.25
0    60.5
Name: score, dtype: float64

In [18]:
print(df.score.quantile(0.25))

60.5

In [19]:
print(df.describe())

           score        age
count   6.000000   6.000000
mean   64.183333  20.166667
std    19.037376   6.493587
min    30.600000  15.000000
25%    60.500000  15.000000
50%    65.250000  17.500000
75%    77.500000  24.500000
max    83.500000  30.000000

In [20]:
df.value_counts()       #  出现的次数

name   score  age
tom    60.5   15     2
alice  30.6   20     1
allen  83.5   30     1
bob    70.0   26     1
jack   80.0   15     1
Name: count, dtype: int64

In [21]:
print(df.drop_duplicates())    #去重

    name  score  age
1    tom   60.5   15
3   jack   80.0   15
4  alice   30.6   20
5    bob   70.0   26
6  allen   83.5   30

In [22]:
df.duplicated(subset=['age'],)   # 查看是否重复

1    False
2     True
3     True
4    False
5    False
6    False
dtype: bool

In [23]:
# 随机采样

df.sample(2)

   name  score  age
1   tom   60.5   15
3  jack   80.0   15

In [24]:
print(df.replace(15, 30))

    name  score  age
1    tom   60.5   30
2    tom   60.5   30
3   jack   80.0   30
4  alice   30.6   20
5    bob   70.0   26
6  allen   83.5   30

In [25]:
df.cumsum()
df.cummin()   # 累计最小值

    name  score  age
1    tom   60.5   15
2    tom   60.5   15
3   jack   60.5   15
4  alice   30.6   15
5  alice   30.6   15
6  alice   30.6   15

In [26]:
# 排序

print(df.sort_index(ascending=False))

    name  score  age
6  allen   83.5   30
5    bob   70.0   26
4  alice   30.6   20
3   jack   80.0   15
2    tom   60.5   15
1    tom   60.5   15

In [27]:
print(df.sort_values(by=['score','age'], ascending=[True, False]))
# by  通过 某一列

    name  score  age
4  alice   30.6   20
1    tom   60.5   15
2    tom   60.5   15
5    bob   70.0   26
3   jack   80.0   15
6  allen   83.5   30

In [28]:
df.nlargest(2, columns='score')    # 也可以是列表
df.nsmallest(2, columns='score')

    name  score  age
4  alice   30.6   20
1    tom   60.5   15

# 案例

In [29]:
data = {
    "姓名": ['张三', '李四' , "王五", "赵六", "钱七"],
    "数学": [85, 92, 78, 88, 95],
    "英语": [90, 88, 85, 92, 80],
    "物理": [75, 80, 88, 85, 90]
}

In [50]:
data1 = pd.DataFrame(data, index= [1, 2, 3, 4, 5])
input = data1.iloc[:, 0:2]

In [31]:
print(data1)

   姓名  数学  英语  物理
1  张三  85  90  75
2  李四  92  88  80
3  王五  78  85  88
4  赵六  88  92  85
5  钱七  95  80  90

In [32]:
dataT = data1.T
dataT

     1   2   3   4   5
姓名  张三  李四  王五  赵六  钱七
数学  85  92  78  88  95
英语  90  88  85  92  80
物理  75  80  88  85  90

In [33]:
data1["总分"] = data1[["数学", "英语", "物理"]].sum(axis=1)
data1["平均分"] = data1[["数学", "英语", "物理"]].mean(axis=1)    # 取多列

In [34]:
data1

   姓名  数学  英语  物理   总分        平均分
1  张三  85  90  75  250  83.333333
2  李四  92  88  80  260  86.666667
3  王五  78  85  88  251  83.666667
4  赵六  88  92  85  265  88.333333
5  钱七  95  80  90  265  88.333333

In [35]:
data1[(data1["数学"] > 90) | (data1["英语"] > 85)]

   姓名  数学  英语  物理   总分        平均分
1  张三  85  90  75  250  83.333333
2  李四  92  88  80  260  86.666667
4  赵六  88  92  85  265  88.333333
5  钱七  95  80  90  265  88.333333

In [36]:
data1.sort_values(by = "总分", ascending = False).head(3)

   姓名  数学  英语  物理   总分        平均分
5  钱七  95  80  90  265  88.333333
4  赵六  88  92  85  265  88.333333
2  李四  92  88  80  260  86.666667

In [37]:
data1.nlargest(3, columns=["总分"])

   姓名  数学  英语  物理   总分        平均分
4  赵六  88  92  85  265  88.333333
5  钱七  95  80  90  265  88.333333
2  李四  92  88  80  260  86.666667

# 案例

In [38]:
data = {
    "产品名称": ["A", "B", "C", "D"],
    "单价": [100, 150, 200, 120],
    "销量": [50, 30, 20, 40]
}
df = pd.DataFrame(data)
df

  产品名称   单价  销量
0    A  100  50
1    B  150  30
2    C  200  20
3    D  120  40

In [39]:
s1 = df["单价"]
s2 = df["销量"]

In [40]:
df["销售额"] = s1 * s2
df["总销售额"] = df["单价"]*df["销量"]

In [41]:
df

  产品名称   单价  销量   销售额  总销售额
0    A  100  50  5000  5000
1    B  150  30  4500  4500
2    C  200  20  4000  4000
3    D  120  40  4800  4800

In [42]:
print("销售额最高：", df["销售额"].max().tolist())
df.nlargest(1, columns=['销售额'])

销售额最高： 5000

  产品名称   单价  销量   销售额  总销售额
0    A  100  50  5000  5000

In [43]:
df.sort_values(by="销售额", ascending=False)

  产品名称   单价  销量   销售额  总销售额
0    A  100  50  5000  5000
3    D  120  40  4800  4800
1    B  150  30  4500  4500
2    C  200  20  4000  4000

# 案例 电商用户行为分析

In [44]:
data = {
    "ID":[101, 102, 103, 104, 105],
    "用户名": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "商品类别":["电子产品", "服饰", "电子产品","家居","服饰"],
    "商品单价":[1200, 300, 800, 150, 200],
    "购买数量":[1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
df

    ID      用户名  商品类别  商品单价  购买数量
0  101    Alice  电子产品  1200     1
1  102      Bob    服饰   300     3
2  103  Charlie  电子产品   800     2
3  104    David    家居   150     5
4  105      Eve    服饰   200     4

In [45]:
# 每位用户消费金额
df["消费总金额"] = df["商品单价"] * df["购买数量"]
df

    ID      用户名  商品类别  商品单价  购买数量  消费总金额
0  101    Alice  电子产品  1200     1   1200
1  102      Bob    服饰   300     3    900
2  103  Charlie  电子产品   800     2   1600
3  104    David    家居   150     5    750
4  105      Eve    服饰   200     4    800

In [46]:
# 消费金额最高的用户
df.nlargest(2, columns="消费总金额")

    ID      用户名  商品类别  商品单价  购买数量  消费总金额
2  103  Charlie  电子产品   800     2   1600
0  101    Alice  电子产品  1200     1   1200

In [47]:
#所有平均消费
print("%.2f"%(df["消费总金额"].mean()))

1050.00

In [48]:
df[df["商品类别"]=="电子产品"]["购买数量"].sum()

np.int64(3)

#  数据收集  数据清洗  数据分析   数据可视化